apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: 327888669413.dkr.ecr.us-east-1.amazonaws.com/nginx-test:config
          envFrom:
            - configMapRef:
                name: nginx-test-config
