apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-config
  namespace: production
data:
  APP_ENV: production
  APP_MESSAGE: "Hello from the production environment"
