apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: master

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: nginx-test-config
    literals:
      - APP_ENV=master
      - APP_MESSAGE=Hello from the master environment UPDATED

secretGenerator:
  - name: nginx-test-secret
    literals:
      - APP_SECRET=super-secret-test-value
